# Spring configuration
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  sql:
    init:
      mode: ALWAYS

# Server configuration
server:
  port : 8080

